### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by 2227056071** [coolfishstudio/game-shake#1]
模仿你的代码来写，为什么有的时候摇动手机能够监测到摇动，有的时候就不能监测到摇动，感觉手机网页卡掉了一样

**Comment by coolfishstudio** [comment]
@2227056071  看一看，你的阀值设定，是否设置过大。其次我这个是模拟版的，如果投入使用的话，是否对每一次请求过程有一个结束判定，即是否是，上次请求未完成，下次请求已发出，多次请求所造成的，目前我所想到的问题原因的可能性只有这两条。
